config/routes.rb
Rails.application.routes.draw do
  resources :users, only: %i[index show]

  resources :foods, only: %i[index new create destroy]

  resources :recipes, only: %i[index show new create destroy] do
    resources :recipe_foods, only: %i[new create edit update destroy]
  end

  resources :public_recipes, only: %i[index show]

  resources :shopping_lists, only: %i[index], path: 'shopping_list'

  devise_for :users, controllers: { registrations: 'users/registrations' }, path: ''
  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :delete_all

  def calculate_total_price(food, current_user)
    total_quantity = 0
    food.recipe_foods.each do |recipe_food|
      total_quantity += recipe_food.quantity if recipe_food.recipe.user_id == current_user.id
    end
    total_quantity * food.price
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :delete_all
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
end

app/models/shopping_list.rb
class ShoppingList < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  # GET /foods or /foods.json
  def index
    @foods = Food.includes(:user).all
  end

  # GET /foods/new
  def new
    authenticate_user!
    @food = Food.new
  end

  # POST /foods or /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to food_url(@food), notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    Food.find(params[:id]).destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price).merge(user_id: current_user.id)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.includes(:user).where(public: true)
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe = Recipe.includes(:user).find(params[:id])
    redirect_to public_recipes_path, alert: 'This recipe is not public.' unless @recipe.public
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  # GET /recipe_foods/new
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.new
  end

  # GET /recipe_foods/1/edit
  def edit
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.find(params[:id])
  end

  # POST /recipe_foods or /recipe_foods.json
  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.new(recipe_food_params)
    if @recipe_food.save
      redirect_to recipe_url(@recipe), notice: 'Recipe food was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.find(params[:id])
    if @recipe_food.update(recipe_food_params)
      redirect_to recipe_url(@recipe), notice: 'Recipe food was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /recipe_foods/1 or /recipe_foods/1.json
  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy

    respond_to do |format|
      format.html { redirect_to recipe_recipe_foods_url, notice: 'Recipe food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe_food
    @recipe_food = RecipeFood.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :food_id).merge(recipe_id: params[:recipe_id])
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show destroy]
  before_action :authenticate_user!

  # GET /recipes or /recipes.json
  def index
    @user = current_user
    @recipes = Recipe.includes(:user).where(user_id: @user.id)
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @user = current_user
    redirect_to recipes_path, alert: 'You are not authorized to view this recipe.' if @recipe.user_id != @user.id
    @ingredients = RecipeFood.includes(:food).where(recipe_id: @recipe.id)
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.includes(:user).find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description,
                                   :public).merge(user_id: current_user.id)
  end
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  before_action :set_shopping_list, only: %i[show edit update destroy]

  # GET /shopping_lists or /shopping_lists.json
  def index
    @foods = Food.includes(recipe_foods: :recipe).all
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">
  <p>
    <strong>Name:</strong>
    <%= food.name %>
  </p>
  <p>
    <strong>Measurement unit:</strong>
    <%= food.measurement_unit %>
  </p>
  <p>
    <strong>Price:</strong>
    <%= food.price %>
  </p>
  <p>
    <strong>User:</strong>
    <%= food.user.name %>
  </p>
</div>

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :measurement_unit, style: "display: block" %>
    <%= form.text_field :measurement_unit %>
  </div>
  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/index.html.erb
<h1>Foods</h1>
<div id="foods">
  <% @foods.each do |food| %>
    <%= render food %>
    <% if food.user_id == current_user.id %>
      <p>
        <%= button_to "Delete Food", food, method: :delete, data: { turbo: false } %>
      </p>
    <% end %>
  <% end %>
</div>
<%= link_to "New food", new_food_path %>

app/views/foods/new.html.erb
<h1>New food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <ul>
      <% if signed_in? %>
        <li> <%= button_to "Sign out", destroy_user_session_path, method: :delete, data: { turbo: false } %> </li>
        <li> <%= link_to "Shopping List", shopping_lists_path %> </li>
      <% else %>
        <li> <%= link_to "Sign in", new_user_session_path %> </li>
        <li> <%= link_to "Sign up", new_user_registration_path %> </li>
      <% end %>
      <li> <%= link_to "Recipes", recipes_path %> </li>
      <li> <%= link_to "Public recipes", public_recipes_path %> </li>
      <li> <%= link_to "Foods", foods_path %> </li>
    </ul>
    <%= yield %>
  </body>
</html>

app/views/public_recipes/_public_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <p>
    <strong>Name:</strong>
    <%= recipe.name %>
  </p>

  <p>
    <strong>Preparation time:</strong>
    <%= recipe.preparation_time %>
  </p>

  <p>
    <strong>Cooking time:</strong>
    <%= recipe.cooking_time %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= recipe.description %>
  </p>

  <p>
    <strong>Public:</strong>
    <%= recipe.public %>
  </p>

  <p>
    <strong>User:</strong>
    <%= recipe.user.name %>
  </p>

</div>

app/views/public_recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <p>
    <strong>Name:</strong>
    <%= recipe.name %>
  </p>

  <p>
    <strong>Preparation time:</strong>
    <%= recipe.preparation_time %>
  </p>

  <p>
    <strong>Cooking time:</strong>
    <%= recipe.cooking_time %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= recipe.description %>
  </p>

  <p>
    <strong>Public:</strong>
    <%= recipe.public %>
  </p>

  <p>
    <strong>User:</strong>
    <%= recipe.user.name %>
  </p>

</div>

app/views/public_recipes/index.html.erb
<h1>Recipes</h1>
<div id="recipes">
  <% @recipes.each do |public_recipe| %>
    <%= render public_recipe %>
    <p>
      <%= link_to "Show this recipe", 'public_recipes/' + public_recipe.id.to_s %>
    </p>
  <% end %>
</div>

app/views/public_recipes/show.html.erb
<%= render @recipe %>
<div>
  <%= link_to "Back to public recipes", public_recipes_path %>
</div>

app/views/recipe_foods/_form.html.erb
<%= form_with(model: recipe_food,url: [@recipe, @recipe_food], data: { turbo: false }) do |form| %>
  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>
  <div>
    <%= form.label :food_id, style: "display: block" %>
    <%= form.select :food_id, Food.all.map { |food| [food.name, food.id] } %>
  </div>
  <div>
    <%= form.submit 'Save' %>
  </div>
<% end %>

app/views/recipe_foods/edit.html.erb
<h1>Editing recipe food</h1>
<%= render "form", recipe_food: @recipe_food %>
<br>
<div>
  <%= link_to "Back to recipe foods", recipe_recipe_foods_path %>
</div>

app/views/recipe_foods/new.html.erb
<h1>New recipe food</h1>
<%= render "form", recipe_food: @recipe_food %>
<br>
<div>
  <%= link_to "Back to recipe", @recipe %>
</div>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, data: { turbo: false }) do |form| %>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :preparation_time, style: "display: block" %>
    <%= form.number_field :preparation_time %>
  </div>
  <div>
    <%= form.label :cooking_time, style: "display: block" %>
    <%= form.number_field :cooking_time %>
  </div>
  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>
  <div>
    <%= form.label :public, style: "display: block" %>
    <%= form.check_box :public %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <p>
    <strong>Name:</strong>
    <%= recipe.name %>
  </p>
  <p>
    <strong>Preparation time:</strong>
    <%= recipe.preparation_time %>
  </p>
  <p>
    <strong>Cooking time:</strong>
    <%= recipe.cooking_time %>
  </p>
  <p>
    <strong>Description:</strong>
    <%= recipe.description %>
  </p>
  <p>
    <strong>Public:</strong>
    <%= recipe.public %>
  </p>
  <p>
    <strong>User:</strong>
    <%= recipe.user.name %>
  </p>
</div>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recipes</h1>

<div id="recipes">
  <% @recipes.each do |recipe| %>
    <%= render recipe %>
    <p>
      <%= link_to "Show this recipe", recipe %>
    </p>
  <% end %>
</div>

<%= link_to "New recipe", new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @recipe %>
<div>
  <%= link_to "Add an ingredient", new_recipe_recipe_food_path(@recipe) %>
</div>
<div>
  <ul>
    <% @ingredients.each do |ingredient| %>
      <li> <%= ingredient.food.name %> </li>
      <li> <%= ingredient.quantity %> <%= ingredient.food.measurement_unit %> </li>
      <li> R <%= '%.2f' % (ingredient.food.price * ingredient.quantity) %> </li>
      <li> <%= link_to "Edit", edit_recipe_recipe_food_path(@recipe, ingredient) %> </li>
      <li>
        <%= button_to "Delete", recipe_recipe_food_path(@recipe, ingredient), method: :delete, data: { confirm: "Are you sure?" } %>
      </li>
    <% end %>
  </ul>
</div>
<div>
  <%= link_to "Back to recipes", recipes_path %>
  <%= button_to "Delete this recipe", recipe_path(@recipe), method: :delete, data: { turbo: false } %>
</div>

app/views/shopping_lists/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Shopping lists</h1>
<div id="shopping_list">
  <ul>
    <% @foods.each do |food| %>
      <% food_total = food.calculate_total_price(food, current_user) %>
      <% if food_total > 0 %>
        <li>
          <%= food.name %>
          R <%= '%.2f' % (food.calculate_total_price(food, current_user)) %>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/users/index.html.erb
<h1>Users</h1>
<div id="users">
  <% @users.each do |user| %>
    <%= user.name %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<div>
  <%= link_to "Back to users", users_path %>
</div>